# hash:sha256:de79305c75d4c6086edc602a5478865502bf17d17256e93c5d0a13304064830b
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    cython \
    gensim \
    inspyred \
    networkx \
    node2vec \
    numpy \
    pandas
